name: address_manager
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  http: ^1.1.0
  google_fonts: ^5.1.0
  mask_text_input_formatter: ^2.5.0
  maps_launcher: ^2.2.0
  flutter_hooks: ^0.18.6
  graphql_flutter: ^5.1.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  http: ^1.1.0

flutter:
  uses-material-design: true
