name: app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  url_launcher: ^6.1.12
  drop_shadow_image: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/6d21f240-a85a-4570-a217-c3b9a37d1924.png"
    background_color: "#1E192C"
    theme_color: "#1E192C"

flutter:
  uses-material-design: true

  assets:
    - assets/
