name: bmi_calculator
description: This is the Flutter Specialist Formation's BMI Calculator challenge project from Digital Innovation One
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  get: ^4.6.5
  font_awesome_flutter: ^10.5.0
  gap: ^3.0.1
  material_symbols_icons: ^4.2665.0
  sqflite: ^2.2.8+4
  sqflite_common_ffi_web: ^0.3.6
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
